"""create service requests

Revision ID: 14ad1b0e2d98
Revises: 60029f3cf37a
Create Date: 2026-10-07 23:41:16.046351

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14ad1b0e2d98'
down_revision: Union[str, Sequence[str], None] = '60029f3cf37a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_code', sa.String(length=50), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('maintenance_mode', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('state', sa.String(length=50), nullable=False),
    sa.Column('requested_start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('requested_end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_requests_customer_id'), 'service_requests', ['customer_id'], unique=False)
    op.create_index(op.f('ix_service_requests_machine_id'), 'service_requests', ['machine_id'], unique=False)
    op.create_index(op.f('ix_service_requests_request_code'), 'service_requests', ['request_code'], unique=True)
    op.create_index(op.f('ix_service_requests_site_id'), 'service_requests', ['site_id'], unique=False)
    op.create_index(op.f('ix_service_requests_state'), 'service_requests', ['state'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_requests_state'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_site_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_request_code'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_machine_id'), table_name='service_requests')
    op.drop_index(op.f('ix_service_requests_customer_id'), table_name='service_requests')
    op.drop_table('service_requests')
    # ### end Alembic commands ###
