"""add warehouse to resource reservations

Revision ID: 3dea119e398d
Revises: 2914901a53da
Create Date: 2026-10-08 04:08:53.047725

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3dea119e398d'
down_revision: Union[str, Sequence[str], None] = '2914901a53da'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resource_reservations', sa.Column('warehouse_id', sa.Integer(), nullable=True))
    op.create_index(op.f('ix_resource_reservations_warehouse_id'), 'resource_reservations', ['warehouse_id'], unique=False)
    op.create_foreign_key(
        'fk_resource_reservations_warehouse_id',
        'resource_reservations',
        'warehouses',
        ['warehouse_id'],
        ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(
        'fk_resource_reservations_warehouse_id',
        'resource_reservations',
        type_='foreignkey',
    )
    op.drop_index(op.f('ix_resource_reservations_warehouse_id'), table_name='resource_reservations')
    op.drop_column('resource_reservations', 'warehouse_id')
    # ### end Alembic commands ###
