"""create request ai analysis

Revision ID: 4c1feb5c4f63
Revises: 14ad1b0e2d98
Create Date: 2026-10-07 23:50:37.463194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4c1feb5c4f63'
down_revision: Union[str, Sequence[str], None] = '14ad1b0e2d98'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_ai_analysis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_id', sa.Integer(), nullable=False),
    sa.Column('issue_type', sa.String(length=100), nullable=True),
    sa.Column('failure_mode', sa.String(length=150), nullable=True),
    sa.Column('severity', sa.String(length=30), nullable=True),
    sa.Column('required_skills', sa.JSON(), nullable=True),
    sa.Column('required_tools', sa.JSON(), nullable=True),
    sa.Column('required_parts', sa.JSON(), nullable=True),
    sa.Column('similar_failures', sa.JSON(), nullable=True),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('model_name', sa.String(length=100), nullable=True),
    sa.Column('analysis_result', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['service_requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_ai_analysis_request_id'), 'request_ai_analysis', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_ai_analysis_request_id'), table_name='request_ai_analysis')
    op.drop_table('request_ai_analysis')
    # ### end Alembic commands ###
