"""add work logs

Revision ID: 706cb9e96573
Revises: 4d6528a12727
Create Date: 2026-10-08 01:29:20.803822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '706cb9e96573'
down_revision: Union[str, Sequence[str], None] = '4d6528a12727'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_request_id', sa.Integer(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=False),
    sa.Column('log_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['service_request_id'], ['service_requests.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_logs_service_request_id'), 'work_logs', ['service_request_id'], unique=False)
    op.create_index(op.f('ix_work_logs_technician_id'), 'work_logs', ['technician_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_work_logs_technician_id'), table_name='work_logs')
    op.drop_index(op.f('ix_work_logs_service_request_id'), table_name='work_logs')
    op.drop_table('work_logs')
    # ### end Alembic commands ###
