"""add service history

Revision ID: c949d45a3392
Revises: 91b2c613e03f
Create Date: 2026-10-08 03:15:23.879158

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c949d45a3392'
down_revision: Union[str, Sequence[str], None] = '91b2c613e03f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('machine_id', sa.Integer(), nullable=False),
    sa.Column('service_request_id', sa.Integer(), nullable=False),
    sa.Column('request_code', sa.String(length=50), nullable=False),
    sa.Column('maintenance_mode', sa.String(length=30), nullable=False),
    sa.Column('priority', sa.String(length=30), nullable=False),
    sa.Column('issue_type', sa.String(length=100), nullable=True),
    sa.Column('failure_mode', sa.String(length=150), nullable=True),
    sa.Column('resolution_summary', sa.Text(), nullable=False),
    sa.Column('technician_id', sa.Integer(), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['machine_id'], ['machines.id'], ),
    sa.ForeignKeyConstraint(['service_request_id'], ['service_requests.id'], ),
    sa.ForeignKeyConstraint(['technician_id'], ['technicians.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_history_machine_id'), 'service_history', ['machine_id'], unique=False)
    op.create_index(op.f('ix_service_history_service_request_id'), 'service_history', ['service_request_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_history_service_request_id'), table_name='service_history')
    op.drop_index(op.f('ix_service_history_machine_id'), table_name='service_history')
    op.drop_table('service_history')
    # ### end Alembic commands ###
