from enum import Enum


class MaintenanceMode(str, Enum):
    REGULAR = "REGULAR"
    REACTIVE = "REACTIVE"
    PREDICTIVE = "PREDICTIVE"


class Priority(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"
    CRITICAL = "CRITICAL"


class ServiceRequestState(str, Enum):
    DRAFT = "DRAFT"
    SUBMITTED = "SUBMITTED"
    CLASSIFYING = "CLASSIFYING"
    VALIDATING = "VALIDATING"
    VALIDATED = "VALIDATED"
    NEEDS_REVIEW = "NEEDS_REVIEW"
    PLANNING = "PLANNING"
    RESOURCE_CHECK = "RESOURCE_CHECK"
    RESOURCES_READY = "RESOURCES_READY"
    BLOCKED_BY_RESOURCE = "BLOCKED_BY_RESOURCE"
    RESOLVING = "RESOLVING"
    PENDING_APPROVAL = "PENDING_APPROVAL"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"
    DISPATCHED = "DISPATCHED"
    ACCEPTED_BY_TECH = "ACCEPTED_BY_TECH"
    IN_PROGRESS = "IN_PROGRESS"
    EXCEPTION = "EXCEPTION"
    REASSIGNMENT_PLANNING = "REASSIGNMENT_PLANNING"
    COMPLETED_PENDING_VERIFICATION = "COMPLETED_PENDING_VERIFICATION"
    VERIFICATION = "VERIFICATION"
    FAILED = "FAILED"
    PASSED = "PASSED"
    CUSTOMER_APPROVAL = "CUSTOMER_APPROVAL"
    CLOSED = "CLOSED"


class AssignmentStatus(str, Enum):
    PROPOSED = "PROPOSED"
    ASSIGNED = "ASSIGNED"
    ACCEPTED = "ACCEPTED"
    REASSIGNMENT_PENDING = "REASSIGNMENT_PENDING"
    COMPLETED = "COMPLETED"
    CANCELLED = "CANCELLED"


class ReservationStatus(str, Enum):
    RESERVED = "RESERVED"
    RELEASED = "RELEASED"
    CONSUMED = "CONSUMED"
    CANCELLED = "CANCELLED"


class ResourceType(str, Enum):
    TECHNICIAN = "TECHNICIAN"
    PART = "PART"
    TOOL = "TOOL"


class ApprovalStatus(str, Enum):
    PENDING = "PENDING"
    APPROVED = "APPROVED"
    REJECTED = "REJECTED"


class ExceptionStatus(str, Enum):
    OPEN = "OPEN"
    INVESTIGATING = "INVESTIGATING"
    RESOLVED = "RESOLVED"
    ESCALATED = "ESCALATED"


class SLAStatus(str, Enum):
    GREEN = "GREEN"
    AMBER = "AMBER"
    RED = "RED"